### ISSUE TITLE
epic(ui): implement a web UI to manage it

### ISSUE THREAD

**Issue by Byloth** [Byloth/cmangos-docker#6]
Implement a web UI to manage the server:

#### On the Administrator side:
- [ ] Statistics about realms load, active users and so on...
- [ ] A way to manage the users (adds new users, ban users, reset user passwords, etc...).

#### On the User side:
- [ ] Register a new account.
- [ ] Reset a forgotten password.
- [ ] Change account informations (e-mail, username, password, etc...).
- [ ] Delete the account.

**Comment by dekuplant** [comment]
https://github.com/celguar/mangos-web
https://github.com/celguar/mangos-website
https://github.com/celguar/cmangos-website
https://github.com/celguar/spp-classics-cmangos
(Not sure which one would work best so I linked them all)

SPP-Classics uses a cool Web Server which gives browser access to Armory, player count, create player account, AH listings, player tracking on map, and more. It's a vanilla blizzlike style too! Just have to open a web browser and visit 127.0.0.1 when the Web Server is up.
I installed SPP-classics on Windows 11 OS and it worked well. Only tried the user side of account control for the web server.
Would love to have this website feature with cmangos-docker. (installed on CachyOS for me).

**Comment by dekuplant** [comment]
<img width="2880" height="1800" alt="Image" src="https://github.com/user-attachments/assets/b62c19ed-4a23-4c50-96c1-b796f51b204b" />

<img width="2880" height="1800" alt="Image" src="https://github.com/user-attachments/assets/07e571ff-901f-4488-8bfe-4633e661842c" />

<img width="2880" height="1622" alt="Image" src="https://github.com/user-attachments/assets/96635192-281f-4f1f-b182-491461125a0a" />

<img width="2880" height="1800" alt="Image" src="https://github.com/user-attachments/assets/a39ed70c-528d-4462-889b-fff0cdfd7b13" />

<img width="2880" height="1800" alt="Image" src="https://github.com/user-attachments/assets/618b0ff4-2293-4ce9-b90c-d45fbc0b7a59" />
